from typing import Dict

classes = [
    "airport_inside",
    "artstudio",
    "auditorium",
    "bakery",
    "bar",
    "bathroom",
    "bedroom",
    "bookstore",
    "bowling",
    "buffet",
    "casino",
    "children_room",
    "church_inside",
    "classroom",
    "cloister",
    "closet",
    "clothingstore",
    "computerroom",
    "concert_hall",
    "corridor",
    "deli",
    "dentaloffice",
    "dining_room",
    "elevator",
    "fastfood_restaurant",
    "florist",
    "gameroom",
    "garage",
    "greenhouse",
    "grocerystore",
    "gym",
    "hairsalon",
    "hospitalroom",
    "inside_bus",
    "inside_subway",
    "jewelleryshop",
    "kindergarden",
    "kitchen",
    "laboratorywet",
    "laundromat",
    "library",
    "livingroom",
    "lobby",
    "locker_room",
    "mall",
    "meeting_room",
    "movietheater",
    "museum",
    "nursery",
    "office",
    "operating_room",
    "pantry",
    "poolinside",
    "prisoncell",
    "restaurant",
    "restaurant_kitchen",
    "shoeshop",
    "stairscase",
    "studiomusic",
    "subway",
    "toystore",
    "trainstation",
    "tv_studio",
    "videostore",
    "waitingroom",
    "warehouse",
    "winecellar",
]


def get_cls2id_map() -> Dict[str, int]:
    cls2id_map = {classes[i] for i in range(len(classes))}
    return cls2id_map


def get_id2cls_map() -> Dict[int, str]:
    cls2id_map = get_cls2id_map()
    return {val: key for key, val in cls2id_map.items()}
